#!/usr/bin/env bash
set -euo pipefail

readonly APP_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
readonly CM33_DIR="${APP_DIR}/cm33_ns"
readonly CM55_DIR="${APP_DIR}/cm55"
readonly CM33_BUILD_DIR="${APP_DIR}/build-cm33-ns"
readonly CM55_BUILD_DIR="${APP_DIR}/build-cm55"
readonly OPENOCD="/opt/Tools/ModusToolboxProgtools-1.7/openocd/bin/openocd"

source /home/wasanw/zephyrproject/.venv/bin/activate
source /home/wasanw/zephyrproject/zephyr/zephyr-env.sh

# The CM55 configure step consumes PSA headers generated by the CM33-NS build.
west build -p auto -d "${CM33_BUILD_DIR}" \
  -b kit_pse84_ai/pse846gps2dbzc4a/m33/ns "${CM33_DIR}" \
  -- -DOPENOCD="${OPENOCD}"
west build -p auto -d "${CM55_BUILD_DIR}" \
  -b kit_pse84_ai/pse846gps2dbzc4a/m55 "${CM55_DIR}" \
  -- -DPSE84_CM33_BUILD_DIR="${CM33_BUILD_DIR}" -DOPENOCD="${OPENOCD}"
