CONFIG_CONSOLE=y
CONFIG_SERIAL=y
CONFIG_FLASH=y
CONFIG_FLASH_MAP=y
CONFIG_FLASH_PAGE_LAYOUT=y
CONFIG_SETTINGS=y
CONFIG_FCB=y
CONFIG_SETTINGS_FCB=y
CONFIG_SETTINGS_FCB_NUM_AREAS=4
CONFIG_REBOOT=y
CONFIG_MAIN_STACK_SIZE=4096
