#!/usr/bin/env python3
"""Test the actual C mounting, ground-zero and barometric estimation math."""
import ctypes as c
import math
import pathlib
import subprocess
import tempfile
from test_attitude import Attitude, Vec

ROOT=pathlib.Path(__file__).resolve().parent
class Frame(c.Structure):
    _fields_=[("r",c.c_float*9)]
class Baro(c.Structure):
    _fields_=[("reference",c.c_float),("altitude",c.c_float),("climb",c.c_float),("initialized",c.c_bool)]

def main():
    with tempfile.TemporaryDirectory(prefix="e84-flight-") as folder:
        output=pathlib.Path(folder)/"flight.so"
        subprocess.run(["cc","-std=c11","-Wall","-Wextra","-Werror","-shared","-fPIC",
                        str(ROOT/"src/flight_math.c"),str(ROOT/"src/attitude.c"),
                        str(ROOT/"src/horizon_draw.c"),"-lm","-o",str(output)],check=True)
        lib=c.CDLL(str(output))
        lib.cockpit_upright.argtypes=[c.POINTER(Frame)]
        lib.cockpit_zero.argtypes=[c.POINTER(Frame),c.c_float,c.c_float]
        lib.cockpit_apply.argtypes=[c.POINTER(Frame),Vec,Vec]
        lib.cockpit_to_pilot.argtypes=[Vec,Vec]
        lib.cockpit_heading.argtypes=[c.c_float]
        lib.cockpit_heading.restype=c.c_float
        lib.cockpit_card_point.argtypes=[c.c_float,c.c_float,c.c_float,c.POINTER(c.c_float)]
        lib.attitude_update.argtypes=[c.POINTER(Attitude),Vec,Vec,c.c_float]
        lib.attitude_update.restype=c.c_bool
        lib.baro_update.argtypes=[c.POINTER(Baro),c.c_float,c.c_float]
        lib.baro_update.restype=c.c_bool
        lib.baro_zero.argtypes=[c.POINTER(Baro),c.c_float]
        lib.baro_zero.restype=c.c_bool
        f=Frame(); lib.cockpit_upright(c.byref(f))
        def apply(v):
            result=Vec(); lib.cockpit_apply(c.byref(f),Vec(*v),result); return tuple(result)
        def inverse(v):
            return tuple(sum(f.r[3*j+i]*v[j] for j in range(3)) for i in range(3))
        def gravity(roll,pitch):
            r,p=map(math.radians,(roll,pitch))
            return (-math.sin(p),math.sin(r)*math.cos(p),math.cos(r)*math.cos(p))
        def pose(native):
            s=Attitude()
            assert lib.attitude_update(c.byref(s),Vec(*apply(native)),Vec(0,0,0),.01)
            return s.roll.angle,s.pitch.angle
        assert apply((0,-1,0))==(0.,0.,1.)
        assert max(abs(v) for v in pose((0,-1,0)))<.01
        assert abs(pose((0,0,1))[1]-90)<.01
        # Both vectors use the same proper rotation: angular velocity is not mirrored.
        assert apply((1,2,3))==(-3.,1.,-2.)
        for roll,pitch in [(20,0),(-20,0),(0,20),(0,-20),(25,30),(-25,-30)]:
            native=inverse(gravity(roll,pitch))
            r,p=pose(native)
            assert abs(r-roll)<.001 and abs(p-pitch)<.001,(r,p)
        print("PASS filter mounting: upright level, flat +90 internal pitch, proper vector rotation")
        # Ground zero composes orthogonal frames rather than subtracting Euler angles.
        for roll,pitch in [(25,30),(0,89),(-40,-35)]*20:
            native=inverse(gravity(roll,pitch))
            lib.cockpit_zero(c.byref(f),roll,pitch)
            assert max(abs(v) for v in pose(native))<.003
            a,b,d=(f.r[i:i+3] for i in (0,3,6))
            determinant=a[0]*(b[1]*d[2]-b[2]*d[1])-a[1]*(b[0]*d[2]-b[2]*d[0])+a[2]*(b[0]*d[1]-b[1]*d[0])
            assert abs(determinant-1)<.0001
            for axis in range(3):
                assert abs(sum(f.r[3*axis+i]**2 for i in range(3))-1)<.0001
        lib.cockpit_upright(c.byref(f)); assert apply((0,-1,0))==(0.,0.,1.)
        print("PASS ground zero: tilted/near-vertical references, repeated proper rotations, default restore")
        def pilot(angles):
            result=Vec(); lib.cockpit_to_pilot(Vec(*angles),result); return tuple(result)
        def native_update(s,a,w=(0,0,0)):
            assert lib.attitude_update(c.byref(s),Vec(*apply(a)),Vec(*apply(w)),.01)
            return pilot((s.roll.angle,s.pitch.angle,s.yaw))
        # Independent native vectors anchored to the user's physical videos,
        # not generated by inverting the implementation under test.
        # Panel top TOWARD pilot = nose up; native Z becomes negative.
        for sign in (-1,1):
            s=Attitude(); native_update(s,(0,-1,0))
            for i in range(1,201):
                p=sign*math.radians(20)*i/200
                bank,pitch,yaw=native_update(s,(0,-math.cos(p),-math.sin(p)),
                                            (-sign*math.radians(10),0,0))
            assert abs(pitch-sign*20)<.3 and abs(bank)<.1,(bank,pitch)
            # Ground zero MUST consume internal angles, not sign-converted pitch.
            lib.cockpit_zero(c.byref(f),s.roll.angle,s.pitch.angle)
            s=Attitude(); angles=native_update(s,(0,-math.cos(p),-math.sin(p)))
            assert max(abs(v) for v in angles)<.01,angles
            lib.cockpit_upright(c.byref(f))
        assert abs(pilot((*pose((0,0,1)),0))[1]+90)<.01
        print("PASS pilot pitch: top toward = +20/nose-up, away = -20/nose-down; gyro agrees; ground zero works for both")
        # Clockwise/right heading corresponds to +native Y angular velocity.
        for sign,expected in [(1,90),(-1,270)]:
            s=Attitude(); native_update(s,(0,-1,0))
            for _ in range(100): angles=native_update(s,(0,-1,0),(0,sign*math.pi/2,0))
            heading=lib.cockpit_heading(angles[2])
            assert abs(heading-expected)<.2,(angles,heading)
            turn=pilot(apply((0,sign*math.pi/2,0)))[2]
            assert turn*sign>0
        for bank in (-25,25):
            phi=math.radians(bank)
            measured=pilot((*pose((math.sin(phi),-math.cos(phi),0)),0))
            assert abs(measured[0]-bank)<.001
        print("PASS pilot heading/rate: right +90 => 090, left -90 => 270; bank signs unchanged")
        for yaw,expected in [(0,0),(-0.0,0),(-90,270),(90,90),(180,180),(-180,180),
                             (359.96,0),(-.04,0),(-.06,359.9),(720,0),(-450,270)]:
            h=lib.cockpit_heading(yaw)
            assert 0<=h<360 and abs(h-expected)<.001,(yaw,h)
        print("PASS heading wrap: 000..359.9, no negative or rounded 360.0 display")
        def card_point(heading,mark,radius=47):
            point=(c.c_float*2)()
            lib.cockpit_card_point(heading,mark,radius,point)
            return tuple(point)
        for heading in range(360):
            x,y=card_point(heading,heading,70)
            assert abs(x)<.001 and abs(y+70)<.001  # selected heading at fixed top marker
            boxes=[]
            for mark in (0,90,180,270):
                x,y=card_point(heading,mark)
                x,y=round(76+x),round(76+y)
                box=(x-18,y-8,x+18,y+8)  # upright 36 x 16 label, never rotated
                assert all(math.hypot(px-76,py-76)<76
                           for px in (box[0],box[2]) for py in (box[1],box[3]))
                for other in boxes:
                    assert box[2]<=other[0] or other[2]<=box[0] or box[3]<=other[1] or other[3]<=box[1]
                boxes.append(box)
        assert card_point(90,0)[0]<-46 and card_point(270,0)[0]>46
        assert math.dist(card_point(359.9,0),card_point(.1,0))<.2
        print("PASS rotating card: selected heading at fixed top, counter-rotation, smooth wrap; upright labels fit without overlap through 360 degrees")
        lib.horizon_draw.argtypes=[c.POINTER(c.c_uint16),c.c_float,c.c_float]
        pixels=(c.c_uint16*(344*344))()
        sky=[]
        for pitch in (-20,0,20):
            lib.horizon_draw(pixels,0,pitch)
            sky.append(sum((v&31)>((v>>11)&31) for v in pixels))
        assert sky[0]<sky[1]<sky[2],sky
        print("PASS pilot horizon: nose up shows more sky, nose down more ground")
        s=Baro()
        assert lib.baro_update(c.byref(s),101.325,.1)
        assert s.altitude==s.climb==0 and s.initialized
        def pressure(height): return 101.325*(1-height/44330)**(1/.19029496)
        for _ in range(200): assert lib.baro_update(c.byref(s),pressure(100),.1)
        assert abs(s.altitude-100)<.03 and abs(s.climb)<.01
        assert lib.baro_zero(c.byref(s),101.325)
        for i in range(1,201): assert lib.baro_update(c.byref(s),pressure(i*.1),.1)
        assert abs(s.climb-1)<.03
        assert lib.baro_zero(c.byref(s),101.325)
        for i in range(1,201): assert lib.baro_update(c.byref(s),pressure(-i*.1),.1)
        assert abs(s.climb+1)<.03
        assert lib.baro_update(c.byref(s),pressure(30),5)
        assert abs(s.altitude-30)<.03 and s.climb==0 and abs(s.reference-101.325)<.001
        for p,dt in [(float("nan"),.1),(0,.1),(121,.1),(100,0),(100,100),(100,float("nan"))]:
            old=bytes(s); assert not lib.baro_update(c.byref(s),p,dt) and bytes(s)==old
        assert lib.baro_zero(c.byref(s),100) and s.altitude==s.climb==0
        print("PASS barometer: units/sign, 100 m altitude, +/-1 m/s climb/descent, ground zero, stale recovery, invalid rejection")

if __name__=="__main__": main()
